# Generated by Django 5.1 on 2024-10-23 23:33

from django.db import migrations

def create_initial_services_and_requirements(apps, schema_editor):
    Requirement = apps.get_model('muni', 'Requirement')
    Service = apps.get_model('muni', 'Service')

    services_data = [
        {
            "service": "Conformación de un Cocode",
            "requirements": [
                "Presentar solicitud dirigida al señor alcalde municipal.",
                "Libro empastado para su habitación y firmas respectivas.",
                "Nombre del cocode y dirección exacta.",
                "Convocar a los vecinos de 18 años hombres y mujeres para elegir a la junta directiva.",
                "Dentro de la directiva deben figurar 3 o 2 mujeres que participen.",
                "Contar con sello respectivo para identificarse.",
                "Tomar fotografías respectivas en la realización de la asamblea.",
                "Copia del acta firmada por todos los asistentes.",
                "Certificación del acta respectiva, firmada y sellada por el secretario(a) presidente(a).",
                "Fotocopia del DPI.",
                "Fotocopia del boleto de ornato.",
                "Tomarse la foto con buena presentación para el carnet.",
                "Si una persona del otro sector tiene propiedad en el sector en donde se conformará el cocode deberá presentar pruebas para ser tomado en cuenta."
            ]
        },
        {
            "service": "Licencia de construcción",
            "requirements": [
                "Comprar formulario en tesorería Q.10.00.",
                "Fotocopia de boleto de ornato.",
                "Fotocopia del DPI.",
                "Fotocopia de la escritura del inmueble.",
                "Plano del terreno con medidas y colindancias.",
                "Plano de la construcción con las medidas exactas.",
                "Estudio de impacto ambiental."
            ]
        },
        {
            "service": "Constancia de residencia de magisterio",
            "requirements": [
                "Fotocopia del DPI.",
                "Fotocopia de boleto de ornato.",
                "Fotocopia del recibo de energía eléctrica o agua potable (que tenga la dirección exacta y reciente, caso contrario presentar constancia de nomenclátor dura emitida por la oficina de síndicos municipales).",
                "Fotocopia de cédula de docente.",
                "El trámite se realiza en secretaría municipal.",
                "Pago en tesorería municipal (Q.10.00)."
            ]
        },
        {
            "service": "Instalación de postes de energía eléctrica",
            "requirements": [
                "Formulario para instalación de postes de energía eléctrica (adquirir en tesorería municipal).",
                "Fotocopia del DPI.",
                "Fotocopia de boleto de ornato.",
                "Fotocopia de la escritura completa.",
                "Fotocopia de la licencia de construcción.",
                "Copia del derecho de paso de línea de energía eléctrica firmada por los vecinos.",
                "El trámite se realiza en secretaría municipal."
            ]
        },
        {
            "service": "Avales de energía eléctrica",
            "requirements": [
                "Fotocopia del DPI.",
                "Fotocopia de boleto de ornato.",
                "Fotocopia de la escritura completa.",
                "Copia de licencia de construcción o constancia de nomenclatura.",
                "Pago en tesorería municipal (Q.15.00).",
                "El trámite se realiza en secretaría municipal."
            ]
        },
        {
            "service": "Constancia de residencia",
            "requirements": [
                "Fotocopia del DPI.",
                "Fotocopia de boleto de ornato.",
                "Fotocopia del recibo de energía eléctrica o agua potable (que tenga la dirección exacta y reciente, caso contrario presentar constancia de nomenclátor dura emitida por la oficina de síndicos municipales).",
                "El trámite se realiza en secretaría municipal.",
                "Pago en tesorería municipal (Q.10.00)."
            ]
        },
        {
            "service": "Solicitud de servicio de 1/2 Paja de agua potable y conexión a drenaje",
            "requirements": [
                "Compra de solicitud de servicio de agua, valor Q.10.00 (comprar en tesorería).",
                "Compra de contrato, valor Q.40.00 (compra en tesorería).",
                "Fotocopia del DPI.",
                "Fotocopia de NIT.",
                "Fotocopia de la escritura del inmueble (terreno donde se construirá).",
                "Fotocopia de boleto de ornato.",
                "Constancia de aporte derecho de adoquinado o pago de drenaje.",
                "Compra de solicitud de servicio de drenaje, valor Q.10.00 (compra en tesorería).",
                "Fotocopia de: licencia de construcción o constancia de nomenclatura (dirección del municipio).",
                "Nombres y apellidos, dirección y teléfono de 2 referencias (1 familiar y 1 personal)."
            ]
        }
    ]

    for service_data in services_data:
        service = Service.objects.create(
            title=service_data['service'],
            description=service_data['service']
        )
        for req_desc in service_data['requirements']:
            r = Requirement.objects.get_or_create(description=req_desc)
            service.requirements.add(r[0])

def remove_initial_services_and_requirements(apps, schema_editor):

    Requirement = apps.get_model('muni', 'Requirement')
    Service = apps.get_model('muni', 'Service')

    Service.objects.all().delete()
    Requirement.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('muni', '0006_alter_requirement_options'),
    ]

    operations = [
        migrations.RunPython(create_initial_services_and_requirements, remove_initial_services_and_requirements),
    ]
